[package]
name = "serde1400"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json_1400 = { version = "1.0.87", path = "../../" }
serde = { version = "1.0", features = ["derive"] }